FROM docker.io/library/python:3.11

WORKDIR /app

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu --no-cache-dir
RUN pip3 install 'transformers[torch]' sentencepiece --no-cache-dir

COPY . .

RUN python3 dry-run.py

CMD [ "python3" ]
